Nikol
dpeshevski/semos-html-css-generation-13 pull request #12
Opened 2021-04-05 16:00 UTC by Nikolina5

Daniel please check my homework.

2021-04-06 13:58 UTC, Metodija-Mitovski commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +        <h4>Here are more informations about us!<img src="../lecture2/static/images/cekan.png" alt="cekan"  width="40px" height="40px" /></h4>
heading елементите подобро би било да се користат само за текст без дополнителни тагови во нив и надвор од header

2021-04-06 14:00 UTC, Metodija-Mitovski reviewed
Ми се допадна уредноста.Лесно читлив код .. :)

2021-04-06 14:06 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +        <h4>Here are more informations about us!<img src="../lecture2/static/images/cekan.png" alt="cekan"  width="40px" height="40px" /></h4>
Благодарам. Изгледа ми посочуваш да не ставам линк на heading тагови. Зошто мислиш дека така е подобро? Те молам пиши ми. :)

2021-04-06 14:22 UTC, Metodija-Mitovski commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +        <h4>Here are more informations about us!<img src="../lecture2/static/images/cekan.png" alt="cekan"  width="40px" height="40px" /></h4>
Вообичаено heading елементите се наменети за даванје на краток опис на контентот што се наоѓа под нив.
пр. Наслов на секција, некаков поднаслов во самата секција со помал heading ... Така кога скроламе на некоја web страна лесно добиваме претстава кај се наоѓаме на самата страна.

2021-04-06 15:05 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +        <h4>Here are more informations about us!<img src="../lecture2/static/images/cekan.png" alt="cekan"  width="40px" height="40px" /></h4>
Има смисла. Ти благодарам многу.

2021-04-06 16:59 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +        <h4>Here are more informations about us!<img src="../lecture2/static/images/cekan.png" alt="cekan"  width="40px" height="40px" /></h4>
heading element moze da odi vo `nav` samo ako e kratok tekst (nema standard no ete do max 3 words), se sto e povekje e recenica i kje zafakja golem del od layout-ot na stranata.

zosto `img` vo `h1` i `h4`?

2021-04-06 17:04 UTC, dpeshevski reviewed
popravi gi zabeleskite ostaveni dosega i komitiraj za da moze da go prifatam reshenieto.

2021-04-06 17:04 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/GoogleDocs.html
> +
ups, prazen html :)

2021-04-06 19:23 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/GoogleDocs.html
> +
Moja greska. Ke go sredam i ova ne mi bese jasno pa go ostaviv i uste nekolku mi ostanaa pa ke gi dodadam. Thanks :)

2021-04-06 19:26 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +        <h4>Here are more informations about us!<img src="../lecture2/static/images/cekan.png" alt="cekan"  width="40px" height="40px" /></h4>
Img vo h1 staviv za da pokazam deka znam da stavam tekst i slika na ista linija, deka toa vezbavme, nesakav da pravam mnogu povekje na stranata, basic, pa resiv da stavam mala slikicka posle naslovot da mi e ubava stranicata, da ne ja trupam ,samo  zatoa :)

2021-04-07 09:00 UTC, meto2208 commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/NewYork.html
> +</html>
Супер.

2021-04-08 18:13 UTC, dpeshevski reviewed
@Nikolina5 imash ushte nekolku raboti za koregiranje. Pozdrav

2021-04-08 18:13 UTC, dpeshevski commented on lecture3/vezba.html
> +            </thead>
thead se zatvora pred da go otvorish tbody.

2021-04-08 18:13 UTC, dpeshevski commented on lecture3/vezba.html
> +                </tr>
tuka treba da go premestis `</thead>`

2021-04-08 18:13 UTC, dpeshevski commented on lecture3/vezba.html
> +
premnogu prazni mesta imash ostaveno vo kod ovde i pogore.

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/BestFeatures.html
> +                        </ol>
togash tuka treba da ja zatvorish listata za Dva.

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/BestFeatures.html
> +                        </ol>
kako treba da izgleda ova? mozhe da mi objasnis?

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/BestFeatures.html
> +                </ul>
ne mi e jasna cela ul lista

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/movielist.html
> +            </ul>
listata `<li>` ne e zatvorena tuka, dali treba da e ili ne?

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/movielist.html
> +            </ul>
isto i tuka

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +                <h3>Ideas for your home</h3>
ova treba da ti bide so `<li>` namesto so `<h3>`

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/pages/contact-us.html
> +            <li>Living room 36m2 - 50m2</li>
listata ul nema zatvoracki tag :)

2021-04-08 18:13 UTC, dpeshevski commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture3/vezba.html
> +
mnogu prazni mesta postojat vo tr na ovaa page vo kod.

2021-04-09 00:13 UTC, Nikolina5 reviewed
Sekoj ostaven komentar go procitav, kodot go pregledav i gi napraviv potrebnite promeni. I hope it is better now than before :)

2021-04-09 00:13 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/movielist.html
> +            </ul>
Proveriv vo kodot ok e od pricina sto zatvorackite tagovi gi ima na kraj. Imam po tri pati </li> tag eden pod drug na krajot od kodot. Zatoa e okej :)

2021-04-09 00:13 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/movielist.html
> +            </ul>
Da, pak se raboti za glavna lista so podlisti. Isprepletuvanje vo samata sebesi za da se prikazat i podlisti . Pak proveruvav vo kodot i na browser ok e :)

2021-04-09 00:13 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/home-page2.html
> +                <h3>Ideas for your home</h3>
Uste ja nemavme uceno drop-down listata. Mislev tokmu tuka da gi smestam vo drop-down lista so pagacko meni. A moze i so <li> da 👍 Vo idnina ke ja dorazvivam stranicata pa ke premestuvam tagovi i content :) zasega neam skroz ideja kako ke ja pravam zatoa ja ostavam vaka...

2021-04-09 00:13 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture2/pages/contact-us.html
> +            <li>Living room 36m2 - 50m2</li>
Ups,da. Promeneto ! :)

2021-04-09 00:13 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-01/lecture3/vezba.html
> +
:'( neznam kako. Promeneto 👍

2021-04-10 09:16 UTC, emillija approved these changes
good job

2021-04-10 10:16 UTC, VladimirMachkovski commented on students/Nikolina_Eliskovska/homeworks/homework-01/Homework Daniel/BestFeatures.html
> +                </ul>
mislam deka ne ti e dobar kodot . pisi mi od koja list domasha e ovaa

2021-04-10 11:10 UTC, VesnaRosh approved these changes

2021-04-12 20:28 UTC, BojanaMR approved these changes

2021-04-13 12:00 UTC, dpeshevski requested changes
Ti fali folder so outcomes, te molam dodadi gi.

2021-04-18 20:51 UTC, SandraMojsova approved these changes

2021-04-20 12:01 UTC, dpeshevski approved these changes

2021-04-20 12:02 UTC, dpeshevski commented
@Nikolina5 mozes da napravis merge. Have fun :)

2021-04-20 12:04 UTC, merged