adding my first homework
dpeshevski/semos-html-css-generation-13 pull request #13
Opened 2021-04-05 16:17 UTC by BojanaMR

2021-04-06 13:22 UTC, BojanaMR commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/feauturesoftheinternet.html
> +            <h1>The Best Feautures of the Internet</h1>
Greska vo header sum pisuvala ke go popravam 😔

2021-04-06 15:04 UTC, Nikolina5 approved these changes
Се на се ми се допаѓа твојот код Бојана :)

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/cities.html
> +            ________________________________________________________________________________________________________________________________________
ups, za ova ima element `<hr />`

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/cities.html
> +            ________________________________________________________________________________________________________________________________________
isto i tuka

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/feauturesoftheinternet.html
> +            </ol>
celo ova vo `main`, pod `header` :)

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/google-docs-areastolearn.html
> +                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Page</li>
`&nbsp;` ne mora da go koristish, ne se bara 100% tocnost.

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/google-docs-areastolearn.html
> +                        <ol>1.5.Select all</ol>
zosto lista vo lista? zarem ne treba ova da bide `<li>` namesto `<ol>`? sto mislis?

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/google-docs-areastolearn.html
> +                            <ol>2.1.4. Style</ol>
istoto i ovde

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/google-docs-areastolearn.html
> +                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tables</li>
vidi go komentarot pogore za `&nbsp;`

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/hotpot-recipe.html
> +            <center><h1>A Lancashire Hotpot Recipe</h1></center>
zosto `<center>`? zosto se koristi toj element?

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/hotpot-recipe.html
> +        </header>
zosto vo header gi pishuvash ovie raboti? header e sekogas na vrvot od stranata i e sekogas vidliv.

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/hotpot-recipe.html
> +            <center> Lancashire hotpot - a stew originating from Lancashire</center>
**Lancashire hotpot - a stew originating from Lancashire** postoi kako alt vo `<img>` i kako nekakov text vo `<center>`, mozhe da mi kazhesh zosto?

2021-04-06 17:51 UTC, dpeshevski commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/weekly-plan.html
> +                1) &nbsp;Monday
ova ne mozhe so `<ol> Monday </ol>` da se napravi?

2021-04-06 18:25 UTC, BojanaMR commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/cities.html
> +            ________________________________________________________________________________________________________________________________________
Vo red ke go smenam :)

2021-04-06 18:26 UTC, BojanaMR commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/google-docs-areastolearn.html
> +                        <ol>1.5.Select all</ol>
Da da i lva ke go smenam :)

2021-04-06 18:27 UTC, BojanaMR commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/hotpot-recipe.html
> +            <center><h1>A Lancashire Hotpot Recipe</h1></center>
Koga gi staviv vo center mi gi centrirase vo sredina da se pomestat , go najdov od internet sto cepkav i mi rabotese :)

2021-04-06 18:27 UTC, BojanaMR commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/hotpot-recipe.html
> +        </header>
Jasno ke go smenam :)

2021-04-06 18:28 UTC, BojanaMR commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/hotpot-recipe.html
> +            <center> Lancashire hotpot - a stew originating from Lancashire</center>
Ova vo img e greska 
A ova vtorovo go staviv za da mi go pokaze kako tekst pod slikata

2021-04-06 18:30 UTC, BojanaMR commented on students/Bojana_Milanova_Radevski/homeworks/homework-01/weekly-plan.html
> +                1) &nbsp;Monday
Moze ke go smenam , taka i mi bese prvobitno no go vidov ova od kodot na vlado najverojatno bidejki ne mi davase zagrada do brojkata i zatoa vaka go imam smeneto .
Ke go popravam :)

2021-04-10 18:34 UTC, VesnaRosh approved these changes

2021-04-13 12:00 UTC, dpeshevski requested changes
Ti fali folder so outcomes, te molam dodadi gi.

2021-04-18 20:49 UTC, SandraMojsova approved these changes

2021-04-20 16:51 UTC, dpeshevski approved these changes

2021-04-20 16:56 UTC, merged