Stefan homework 02
dpeshevski/semos-html-css-generation-13 pull request #26
Opened 2021-04-08 15:47 UTC by Stefkoo98

Hope u are going to like it :)

2021-04-08 17:48 UTC, dpeshevski commented on students/Stefan_Simjanovski/homworks/homework-01/home-page1.html
> +            <h1><span style="border: 1px solid black;">CROSSFIT</span></h1>
ne ti treba `<span>`

2021-04-08 17:48 UTC, dpeshevski commented on students/Stefan_Simjanovski/homworks/homework-01/home-page1.html
> +            <p><q>CrossFit is a lifestyle characterized by safe, effective exercise and sound nutrition.<br> CrossFit can be used to accomplish any goal, from improved health to weight loss to better
zosto sluzi `<q>`?

2021-04-08 17:48 UTC, dpeshevski commented on students/Stefan_Simjanovski/homworks/homework-01/home-page1.html
> +               </ul>
mozhe da se potrudish za podobra identacija na kod? thanks.

2021-04-08 17:48 UTC, dpeshevski commented on students/Stefan_Simjanovski/homworks/homework-01/pages/categories.html
> +                ><li>Monday
sto oznacuva **>** pred `<li>`?

2021-04-09 09:46 UTC, VladimirMachkovski commented on students/Stefan_Simjanovski/homworks/homework-01/pages/categories.html
> +                ><li>Monday
> vishok ti e. izbrishigo

2021-04-09 09:59 UTC, Metodija-Mitovski commented on students/Stefan_Simjanovski/homworks/homework-01/pages/categories.html
> +                            <pre>50 back extensions</pre>
sto e <pre> ?

2021-04-09 10:00 UTC, Metodija-Mitovski commented on students/Stefan_Simjanovski/homworks/homework-01/pages/categories.html
> +                            <pre>Run 800 meters</pre>
sto e pre ?

2021-04-09 10:28 UTC, Stefkoo98 commented on students/Stefan_Simjanovski/homworks/homework-01/pages/categories.html
> +                ><li>Monday
greska ..

2021-04-09 10:29 UTC, Stefkoo98 commented on students/Stefan_Simjanovski/homworks/homework-01/pages/categories.html
> +                            <pre>Run 800 meters</pre>
za kakko gi pisuvas vo kodot taka da gi pokazuva

2021-04-09 10:30 UTC, Stefkoo98 commented on students/Stefan_Simjanovski/homworks/homework-01/home-page1.html
> +               </ul>
i will .

2021-04-09 10:34 UTC, Stefkoo98 commented on students/Stefan_Simjanovski/homworks/homework-01/home-page1.html
> +            <p><q>CrossFit is a lifestyle characterized by safe, effective exercise and sound nutrition.<br> CrossFit can be used to accomplish any goal, from improved health to weight loss to better
za navodnici pretpostavuvam  ??

2021-04-09 10:35 UTC, Stefkoo98 commented on students/Stefan_Simjanovski/homworks/homework-01/home-page1.html
> +            <h1><span style="border: 1px solid black;">CROSSFIT</span></h1>
gonna correct that. Ty

2021-04-09 12:05 UTC, Metodija-Mitovski commented on students/Stefan_Simjanovski/homworks/homework-01/pages/categories.html
> +                            <pre>Run 800 meters</pre>
ok thanks

2021-04-09 14:56 UTC, meto2208 requested changes

2021-04-09 14:56 UTC, meto2208 commented on students/Stefan_Simjanovski/homworks/homework-01/home-page1.html
> +            <p><q>CrossFit is a lifestyle characterized by safe, effective exercise and sound nutrition.<br> CrossFit can be used to accomplish any goal, from improved health to weight loss to better
Може и со "" , без дополнителни тагови.

2021-04-09 15:27 UTC, emillija approved these changes
super odlicno

2021-04-10 19:59 UTC, ignat-ivanov approved these changes

2021-04-12 12:34 UTC, dpeshevski approved these changes

2021-04-12 17:33 UTC, meto2208 approved these changes

2021-04-12 20:13 UTC, merged