homework02-Strike1
dpeshevski/semos-html-css-generation-13 pull request #28
Opened 2021-04-08 20:38 UTC by emillija

2021-04-09 14:54 UTC, meto2208 requested changes

2021-04-09 14:54 UTC, meto2208 commented on students/Emilija/homeworks/homework-02/index.html
> +                                <tbody>
Одлична работа до сега Емилија, можеш да ги израмниш thead i tbody да бидат во иста линија.

2021-04-09 15:05 UTC, emillija commented on students/Emilija/homeworks/homework-02/index.html
> +                                <tbody>
Fala kolega da si ziv i zdrav mi znaci ova 
Kje gi izramnam vo red

2021-04-09 15:34 UTC, SandraMojsova approved these changes
Super Emilija, prodolzi taka:)

2021-04-09 17:10 UTC, Nikolina5 approved these changes
Emi BRAVO ! Olicno sraboteno :) Eve ti medal 🥇 💯

2021-04-09 17:12 UTC, VesnaRosh commented
Bravo Ema, citliv kod i kreativni tabeli :)

2021-04-10 11:01 UTC, meto2208 approved these changes

2021-04-10 11:02 UTC, VesnaRosh approved these changes

2021-04-10 11:25 UTC, VladimirMachkovski commented on students/Emilija/homeworks/homework-02/index.html
> +
👌👌👌👌👌👌👌

2021-04-10 12:07 UTC, BojanaMR approved these changes

2021-04-12 12:29 UTC, dpeshevski approved these changes

2021-04-12 15:44 UTC, Metodija-Mitovski approved these changes

2021-04-13 11:46 UTC, merged