Feature/homework 03 nikolina
dpeshevski/semos-html-css-generation-13 pull request #29
Opened 2021-04-08 20:56 UTC by Nikolina5

Daniel my homework with the tables is ready :)

2021-04-09 10:14 UTC, BojanaMR commented on students/Nikolina_Eliskovska/homeworks/homework-02/Tables/table1.html
> +                <tbody>
Super izgleda ! 😊

2021-04-09 10:16 UTC, BojanaMR commented on students/Nikolina_Eliskovska/homeworks/homework-02/Tables/table6.html
> +                        <td rowspan="4">Student List</td>
Super citlivo! 🙂 Keep going 👍

2021-04-09 10:16 UTC, BojanaMR approved these changes

2021-04-09 14:50 UTC, meto2208 approved these changes
Oдлично сработено Николина.

2021-04-09 14:50 UTC, meto2208 commented on students/Nikolina_Eliskovska/homeworks/homework-02/Tables/table2.html
> +    <!DOCTYPE html>
Супер изгледа, DOCTYPE html што ти е во body можиш слободно да го избришеш, не ти е потребен.

2021-04-09 14:51 UTC, Nikolina5 commented on students/Nikolina_Eliskovska/homeworks/homework-02/Tables/table2.html
> +    <!DOCTYPE html>
Ups, greska. Fala :)

2021-04-09 15:12 UTC, emillija approved these changes
super odlicno

2021-04-12 12:28 UTC, dpeshevski approved these changes

2021-04-12 20:27 UTC, BojanaMR approved these changes

2021-04-13 11:59 UTC, dpeshevski requested changes
Ti fali folder so outcomes, te molam dodadi gi.

2021-04-18 20:48 UTC, SandraMojsova approved these changes
Nice job

2021-04-20 16:51 UTC, dpeshevski approved these changes

2021-04-20 16:58 UTC, dpeshevski commented
@Nikolina5 sredi gi konfliktite za da moze da se merge :) Pozdrav.

2021-04-22 12:01 UTC, merged