Feature/homework01 sandra
dpeshevski/semos-html-css-generation-13 pull request #32
Opened 2021-04-09 17:51 UTC by SandraMojsova

2021-04-09 20:31 UTC, emillija approved these changes
Good job

2021-04-10 09:44 UTC, dpeshevski requested changes

2021-04-10 09:44 UTC, dpeshevski commented on homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Зошто е празен редот во табелата?

2021-04-10 09:44 UTC, dpeshevski commented on homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Зошто е празен редот во табелата?

2021-04-10 09:44 UTC, dpeshevski commented on students/Sandra_Mojsova/homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Зошто има празен ред?

2021-04-10 09:44 UTC, dpeshevski commented on students/Sandra_Mojsova/homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Зошто има празен ред?

2021-04-10 13:05 UTC, SandraMojsova commented on homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Spored slikata od domasnata, XPath i XSL Transformations, zafakjaat "1,5 red" .
Za da go dobijam toa ,za da napravam takva podelba so rowspan na site td elementi moram da imam i dva prazni reda vo tabelata.

2021-04-10 13:11 UTC, SandraMojsova commented on homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Prviot prazen red go koristam tuka posle XPath , zatoa sto za XPath da zafakja "1,5 red" , dokolku kaj Tuesday koristam rowspan="6" , togas XPath na pola treba da ima rowspan="3" , a ostanatite elementi mi koristat rowspan="2" potreben mi e tuka eden prazen red.

2021-04-10 13:11 UTC, SandraMojsova commented on students/Sandra_Mojsova/homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Prviot prazen red go koristam tuka posle XPath , zatoa sto za XPath da zafakja "1,5 red" , dokolku kaj Tuesday koristam rowspan="6" , togas XPath na pola treba da ima rowspan="3" , a ostanatite elementi mi koristat rowspan="2" potreben mi e tuka eden prazen red.

2021-04-10 13:16 UTC, SandraMojsova commented on students/Sandra_Mojsova/homeworks/homework-02/complex-layout.html
> +            <tr></tr>
Zaradi podelbata so rowspan za da se dobie posakuvaniot efekt od "1,5" red na XSL Transformations, ovoj prazen red mora da go imam tuka i za da narednata redica pocnuvajkji so Wednesday da bide kako sto treba da e.

2021-04-12 12:27 UTC, dpeshevski approved these changes

2021-04-12 20:31 UTC, ignat-ivanov approved these changes

2021-04-13 11:59 UTC, dpeshevski requested changes
Ti fali folder so outcomes, te molam dodadi gi.

2021-04-14 19:16 UTC, SandraMojsova commented
> Ti fali folder so outcomes, te molam dodadi gi.

2021-04-14 19:17 UTC, SandraMojsova commented
> > Ti fali folder so outcomes, te molam dodadi gi.

2021-04-14 20:18 UTC, SandraMojsova commented
> > > Ti fali folder so outcomes, te molam dodadi gi.

Folderot so outcomes e dodaden.

2021-04-20 16:51 UTC, dpeshevski approved these changes

2021-04-20 16:56 UTC, merged