homework-03
dpeshevski/semos-html-css-generation-13 pull request #37
Opened 2021-04-12 14:42 UTC by Metodija-Mitovski

2021-04-12 17:10 UTC, Stefkoo98 approved these changes
Odlicno kolega.

2021-04-13 09:41 UTC, VladimirMachkovski approved these changes
Fenomenalno 👍

2021-04-13 11:37 UTC, emillija requested changes
Kolega ako moze outcomes na toa sto si napravil da vidime kako izgleda domasnoto, inace kodovive ti se bombona :))))

2021-04-13 13:01 UTC, Metodija-Mitovski commented
> 
> 
> Kolega ako moze outcomes na toa sto si napravil da vidime kako izgleda domasnoto, inace kodovive ti se bombona :))))

2021-04-13 13:08 UTC, Metodija-Mitovski commented
> 
> 
> Kolega ako moze outcomes na toa sto si napravil da vidime kako izgleda domasnoto, inace kodovive ti se bombona :))))

@emillija 
Vo outcomes folder se slikite od Daniel sto gi dobivme za domasna ( gi ima na samiot pull request). Mozes da go zemes ovoj branch kaj tebe so pull pa da go razgledas resenieto vo browser kako izleda ako dobro go razvrav prasanjeto ?

2021-04-13 14:15 UTC, emillija commented
> > Kolega ako moze outcomes na toa sto si napravil da vidime kako izgleda domasnoto, inace kodovive ti se bombona :))))
> 
> @emillija
> Vo outcomes folder se slikite od Daniel sto gi dobivme za domasna ( gi ima na samiot pull request). Mozes da go zemes ovoj branch kaj tebe so pull pa da go razgledas resenieto vo browser kako izleda ako dobro go razvrav prasanjeto ?

@Metodija-Mitovski 
Vo tvoj folder "outcomes" napravi screen shots od toa kako ti izgledaat stranite, za da se gleda resenieto sto si go napravil so kodot. Kaj mene ako go povlecam (ili bilo koj drug) nema da go pokaze pravilno kako sto e...

2021-04-13 15:15 UTC, Metodija-Mitovski commented
@emillija 
sega te razbrav ti blagodaram za informacija.
 ima pormeni so nov folder "solution-screenshoots." Te molam proveri dali gi ima, dali moze da gi povleces kaj tebe

2021-04-13 15:15 UTC, emillija approved these changes
Good job! :)

2021-04-13 15:16 UTC, emillija commented
> @emillija
> sega te razbrav ti blagodaram za informacija.
> ima pormeni so nov folder "solution-screenshoots." Te molam proveri dali gi ima, dali moze da gi povleces kaj tebe

Gi pokazuva, ne mora da se povlekuvaat. Super e se, bravo stvarno!

2021-04-13 20:30 UTC, pavlovskim commented
odlicno e 👍

2021-04-14 17:17 UTC, meto2208 approved these changes
Nice work 👍

2021-04-18 20:46 UTC, SandraMojsova approved these changes
Nice job 👏

2021-04-20 16:46 UTC, dpeshevski approved these changes

2021-04-20 16:57 UTC, merged