Add files via upload
dpeshevski/semos-html-css-generation-13 pull request #4
Opened 2021-04-04 18:12 UTC by pavlovskim

2021-04-05 13:20 UTC, dpeshevski reviewed
@pavlovskim Matej, sodrzinata na stranite e skoro identicna na site. Trebalo da se potrudish barem da go smenish i prilagodish spored sekoja stranica. Postoi samo eden mal tekst koj stho ne pokazuva nistho na taa strana. Header e bukvalno copy-pasted od toa shto jas go pokazuvav na predavanjeto. Ocekuvam da go prerabotish. 
Ova ne e prva domashna, ubavo e oznaceno i objasneto na Slack koi pages treba da se pravat vo homework-01, ako ne ti e jasno slobodno prashaj. Pozdrav.

2021-04-05 13:20 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +<html>
ne ureden html code, losha identacija..

2021-04-05 13:20 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +				<h3> <a href ="home.html"><img src="static/images/homepage-icon-png-10.jpg" alt="Home Page" width="33" height="33"></a>	<i>	Zdravo dobredojdovte na mojata prva strana!</i></h3>
vo heading ne se stava link i slika.

2021-04-05 13:20 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +				<h3> <a href ="home.html"><img src="static/images/homepage-icon-png-10.jpg" alt="Home Page" width="33" height="33"></a>	<i>	Zdravo dobredojdovte na mojata prva strana!</i></h3>
heading ne se stava vo header

2021-04-05 13:20 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +				<li><a href="C:\Users\pavlo\Desktop\Domasni semos-web-dev\Homework 2\categories\sports.html">Sports </a></li>
lista treba da pocnuva so parent tag dali e ordered ili unordered, toa tuka go nema.

2021-04-05 13:20 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +			<br />
ne se stava break line megju content..

2021-04-05 13:20 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/products.html
> +						<li>0.70 $uro</li>
$uro sto oznacuva?

2021-04-05 13:20 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/products.html
> +					</ul>
zosto na sekoja lista stavash ul???

2021-04-07 08:37 UTC, meto2208 commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/products.html
> +				<h3> <a href ="home.html"><img src="static/images/homepage-icon-png-10.jpg" alt="Home Page" width="33" height="33"></a>	<i>	Zdravo dobredojdovte na mojata prva strana!</i></h3>
Матеј heading елемент не оди во header, друга забелешка е што имаш други елементи во heading, пробај да не го правиш тоа.Поздрав

2021-04-13 12:02 UTC, dpeshevski requested changes
Ti fali folder so outcomes, te molam dodadi gi.

2021-04-22 09:25 UTC, dpeshevski approved these changes

2021-04-22 09:25 UTC, merged