Upload my first homework
dpeshevski/semos-html-css-generation-13 pull request #7
Opened 2021-04-04 19:13 UTC by pavlovskim

2021-04-06 15:48 UTC, Metodija-Mitovski reviewed
кодот е малце тежок за читање, во header img таг да не биде во heading, самиот heading не е потребен во header

2021-04-06 18:17 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +				<hr>
ne ti treba `<hr>` vo heading.

2021-04-06 18:17 UTC, dpeshevski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +				<h3> <a href ="home.html"><img src="static/images/homepage-icon-png-10.jpg" alt="Home Page" width="33" height="33"></a>	<i>	Zdravo dobredojdovte na mojata prva strana!</i></h3>
Dolg e tekstot za da bide vo header, mozhesh da go skratish ili da go izvadish od header.

2021-04-10 09:09 UTC, emillija commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories/sports.html
> +			</header>
zosto volku mnogu napisano vo header?

2021-04-10 09:09 UTC, emillija commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/products.html
> +		</body>
ne si zatvoril html tuka

2021-04-10 09:09 UTC, emillija commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/home.html
> +                <p>Hello Welcome to the Home Page !</p>
vo main treba da ti se listite od domasno

2021-04-10 09:34 UTC, VladimirMachkovski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories.html
> +				<li><a href="C:\Users\pavlo\Desktop\Domasni semos-web-dev\Homework 2\categories\sports.html">Sports </a></li>
ovie 2 listi stavigi vo <ul> </ul>

2021-04-10 09:48 UTC, VladimirMachkovski commented on students/Matej_Pavlovski/homeworks/homework-01/Homework 1/categories/well-being.html
> +				<nav>
ne mora da imash nav

2021-04-13 12:02 UTC, dpeshevski requested changes
Ti fali folder so outcomes, te molam dodadi gi.

2021-04-18 20:54 UTC, SandraMojsova approved these changes

2021-04-22 09:25 UTC, dpeshevski approved these changes

2021-04-22 09:31 UTC, closed without merging

2021-04-22 09:31 UTC, pavlovskim commented
👍